name: CI

on:
  push:
    branches: [ ** ] # All branches
  pull_request:
    branches: [ main ] # Main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: TypeScript compilation check
      run: npm run build
      
    - name: Lint
      run: npm run lint