name: Create Beta Pre-release

on:
  push:
    branches:
      - beta # Trigger when code is pushed/merged to beta

# Permissions needed to create releases and tags
permissions:
  contents: write

jobs:
  create_prerelease:
    name: Create Beta Pre-release
    runs-on: ubuntu-latest
    # This job assumes that the code pushed to 'beta' has already passed CI checks
    # (e.g., via the ci.yml workflow on a PR or the push itself).

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for potential changelog generation

      - name: Get version from package.json
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Beta Pre-release
        uses: ncipollo/release-action@v1
        with:
          # GITHUB_TOKEN is automatically provided
          tag: v${{ steps.package_version.outputs.version }}-beta.${{ github.run_number }}
          name: Pre-release v${{ steps.package_version.outputs.version }}-beta (Build ${{ github.run_number }})
          body: |
            Automated beta pre-release.
            Version: ${{ steps.package_version.outputs.version }}
            Branch: beta
            Build: ${{ github.run_number }}
            Refer to commit history for detailed changes.
          prerelease: true
          draft: false
          # allowUpdates: true # Consider if you might push multiple times for the same version to beta
