name: Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issue configuration
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed in 7 days if no further activity occurs. Thank you for your contributions.
          close-issue-message: |
            This issue was closed because it has been stale for 7 days with no activity.
          stale-issue-label: 'stale'
          days-before-stale: 60
          days-before-close: 7
          
          # PR configuration
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 7 days if no further activity occurs. Thank you for your contributions.
          close-pr-message: |
            This pull request was closed because it has been stale for 7 days with no activity.
          stale-pr-label: 'stale'
          days-before-pr-stale: 30  # PRs become stale faster than issues
          days-before-pr-close: 7
          
          # Exempt labels - issues/PRs with these labels won't be marked as stale
          exempt-issue-labels: 'pinned,security,bug,enhancement,good first issue,help wanted'
          exempt-pr-labels: 'pinned,security,work-in-progress,do-not-merge'
          
          # Additional configuration
          exempt-draft-pr: true  # Don't mark draft PRs as stale
          remove-stale-when-updated: true  # Remove stale label when updated
          operations-per-run: 100  # Limit operations to avoid rate limiting
          
          # Only process issues/PRs, not both in same run for better performance
          only-labels: ''  # Process all unless they have exempt labels
